name: TailorTripAI API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry && poetry install --only dev
      - name: Lint with flake8
        run: |
          poetry run flake8 .  --statistics
      - name: Typehint with mypy
        run: |
          poetry run mypy .
      - name: Check formatting
        run: poetry run black . --check
      - name: Check isort imports
        run: |
          poetry run isort . --check-only
